### ISSUE TITLE
Align colours with website

### ISSUE THREAD

**Issue by starcaster2018** [openlawnz/openlawnz-search#39]
Current advanced search tan/gold button colours and copy do not match the main site. Pease amend. 

Should be: #a36633

![Screen Shot 2020-02-04 at 12 24 14 pm](https://user-images.githubusercontent.com/42902517/74299630-65ba4100-4da1-11ea-94a5-a07338b3caaa.png)

**Comment by haslamed** [comment]
Hi @starcaster2018 - that's an issue for openlawnz-web. This repo only contains the underlying search API.
I can't transfer the issue, so I'll close this one. Can you please reopen on openlawnz-web?

**Comment by starcaster2018** [comment]
> Hi @starcaster2018 thanks for noting this - although that's an issue for openlawnz-web. This repo only contains the underlying search API.
> I can't transfer the issue, so I'll close this one. Can you please reopen on openlawnz-web?


Sorry, yes ill post it over there.
